%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Dominik\Documents\MATLAB\cas3dTool\CAS3dResultsSummary3.1.xls
%    Worksheet: CAS3dResultsSummary3.1
%
% Auto-generated by MATLAB on 01-Feb-2019 12:42:54

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "CAS3dResultsSummary3.1";
opts.DataRange = "B1:I1";

% Specify column names and types
% opts.VariableNames = [ "CAS3d", "intWeightedCAS3d", "MainDirection", "MainElevation", "WeightedAngularDeviation", "AngularDeviation", "Saturation", "Background"];
% opts.VariableTypes = [ "string", "string", "string", "string", "string", "string", "string", "string"];
% opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "EmptyFieldRule", "auto");

% Import the data
columnHeaders = readtable("C:\Users\Dominik\Documents\MATLAB\cas3dTool\CAS3dResultsSummary3.1.xls", opts, "UseExcel", false);

%% Convert to output type
columnHeaders = table2cell(columnHeaders);
numIdx = cellfun(@(x) ~isnan(str2double(x)), columnHeaders);
columnHeaders(numIdx) = cellfun(@(x) {str2double(x)}, columnHeaders(numIdx));

%% Clear temporary variables
clear  opts